name: CI

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12

      - name: Make Debug folder
        run: mkdir Debug

      - name: Build project
        run: |
          cmake -S . -B Debug -D CMAKE_BUILD_TYPE=Debug
          cmake --build Debug

      - name: Upload Debug release
        uses: actions/upload-artifact@v2
        with:
          name: "spotifyEnableDevTools-Debug"
          path: Debug/Debug/spotifyEnableDevTools.exe
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12

      - name: Make Release folder
        run: mkdir Release

      - name: Build project
        run: |
          cmake -S . -B Release -D CMAKE_BUILD_TYPE=Release
          cmake --build Release --config Release

      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: "spotifyEnableDevTools"
          path: Release/Release/spotifyEnableDevTools.exe
